---
---
<br>

This website contains instructional material for workshops offered at the International Conference on Health Policy Statistics, San Diego, Jan 6-8, 2020. 

Use the navbar at the top, 

<br>
<br>

## `r emo::ji("book")` Producing high-quality, reproducible reports using R and Markdown
#### Instructor: Reid Otsuji, UC San Diego Library

#### Summary
_Data analysts tend to write a lot of reports, describing their analyses and results, for their collaborators or to document their work for future reference. When we first start out, we often write an R script with all of the work, and would just send emails to collaborators, describing the results and attaching various graphs. In discussing the results, there often can be confusion about which graph was which._
_Moving to writing formal reports, with Word or LaTeX, there is still much time spent on getting the figures to look right. Mostly, the concern is about page breaks and generating reproducible results. Imagine the work that has to be done to find the right analysis code to fix a problem in a report generated 4 years ago on an old data set, that you hope you can still find._
_Ideally, such analysis reports are reproducible documents: If an error is discovered, or if some additional subjects are added to the data, you can just re-compile the report and get the new or corrected results (versus having to reconstruct figures, paste them into a Word document, and further hand-edit various detailed results)._
_This workshop will walk you through a key package in R called `knitr`, that is the leading solution to these types of reports. It allows you to create a document that is a mixture of text and chunks of code. When the document is processed by knitr, chunks of code will be executed, and graphs or other results inserted into a professional looking final document. Reports can be created in many formats such as Word, PDF or as HTML webpages, and are highly customizable._

#### Pre-requisites / Required Software
* Prior knowledge of R is helpful, but not necessary. 


----

## `r emo::ji("world")` Promote  yourself - make your own professional website without knowing HTML
### Instructor: [Robin Donatello](www.norcalbiostat.com), California State University, Chico

#### Overview: 
_Linkedin is great, your department or office website may have a bio on a page for you, but you need your own space to share your work. To demonstrate your talent, share recent projects or research, create and curate scientific content. Share your course lecture notes, blog about your recent research, or present analysis results in all their grisly detail as a supplement to a presentation or manuscript. This hands-on workshop will walk you through the process of creating two types of websites with no knowledge of HTML or CSS needed. The first type is a simple site that links a series of web pages you create using the Markdown language together into a website framework. This is ideal for a small project, such as presenting class materials, or an interactive dashboard. The second type of website is ideal for users who wish to write a blog or present a more “modern” feel to their website. This website uses the website generator Hugo, but again no knowledge of Hugo will be necessary. We will use the R studio environment to build these websites using Markdown, and demonstrations of how live code and output can be shown in these webpages, but no direct knowledge of R is required._

#### Pre-requisites / Required Software
* R, R Markdown, version control (e.g. git), GitHub

